//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrowseInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> LoginId { get; set; }
        public string BrowseUrl { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<System.DateTime> BrowseTime { get; set; }
    
        public virtual LoginInfo LoginInfo { get; set; }
    }
}
