//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Des { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<decimal> PropertyFee { get; set; }
        public Nullable<int> CarPortNum { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    }
}
