//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.Permissions = new HashSet<Permission>();
            this.Resource1 = new HashSet<Resource>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string PageName { get; set; }
        public string Des { get; set; }
        public string Url { get; set; }
        public string Parent { get; set; }
        public string ResourceType { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<Resource> Resource1 { get; set; }
        public virtual Resource Resource2 { get; set; }
    }
}
